# Generated by Django 3.2.6 on 2021-09-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20210916_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='forget_password',
        ),
    ]
